---
- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Apply netplan
  ansible.builtin.command: netplan apply
