all:
  children:
    control_node:
      hosts:
        av-control-node:
          ansible_host: 172.23.23.27
          av_management_interface: eth0
          av_management_interface_mac: 00:15:5d:01:1c:08
          av_management_address: 172.23.23.27/20
          av_management_gateway: 172.23.16.1
          av_management_dns_servers:
            - 172.23.16.1
          av_management_search_domains:
            - mshome.net
    repo_vm:
      hosts:
        av-repo-vm:
          ansible_host: 172.23.27.229
          av_management_interface: eth0
          av_management_interface_mac: 00:15:5d:01:1c:09
          av_management_address: 172.23.27.229/20
          av_management_gateway: 172.23.16.1
          av_management_dns_servers:
            - 172.23.16.1
          av_management_search_domains:
            - mshome.net
    build_vm:
      hosts:
        av-build-vm:
          ansible_host: 172.23.30.254
          av_management_interface: eth0
          av_management_interface_mac: 00:15:5d:01:1c:0a
          av_management_address: 172.23.30.254/20
          av_management_gateway: 172.23.16.1
          av_management_dns_servers:
            - 172.23.16.1
          av_management_search_domains:
            - mshome.net
    pxe_client_image:
      hosts:
        av-build-vm:
