all:
  children:
    control_node:
      hosts:
        av-control-node:
          ansible_host: 172.23.23.27
    repo_vm:
      hosts:
        av-repo-vm:
          ansible_host: 172.23.27.229
    build_vm:
      hosts:
        av-build-vm:
          ansible_host: 172.23.30.254
    pxe_client_image:
      hosts:
        av-build-vm:
