all:
  children:
    control_node:
      hosts:
        av-control-node:
          ansible_host: 172.31.116.115
    repo_vm:
      hosts:
        av-repo-vm:
          ansible_host: 172.31.122.189
    build_vm:
      hosts:
        av-build-vm:
          ansible_host: 172.31.124.225
    pxe_client_image:
      hosts:
        av-build-vm:
